markdown: redcarpet
redcarpet: 
  extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline", "autolink"]
permalink: /:year/:month/:title/
url: http://302sk.github.io
author: kun
pygments: true
paginate: 24
