#markdown: rdiscount
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:year/:month/:title/
url: http://302sk.github.com
author: 302sk
pygments: true
paginate: 24
